import Head from 'next/head';
// import Image from 'next/image'
// import { Inter } from '@next/font/google'
// import styles from '@/styles/Home.module.css'
import { useState } from 'react';
import Modal from '@/components/Modal';
import Logo from '@/components/Logo';
import SignUpForm from '@/components/SignUpForm';
import { SubmitResponse } from '@/types/api';

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [isProcessing, setIsProcessing] = useState(false);
  const [submitStatus, setSubmitStatus] = useState<SubmitResponse | null>(null);
  const bgColor = { backgroundColor: '#fcd6e8' };

  function dismissModal() {
    setIsProcessing(false);
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='h-screen' style={bgColor}>
        <Modal
          dismiss={dismissModal}
          status={submitStatus}
          show={isProcessing}
        />
        <div className='flex h-full'>
          <article className='w-full rounded-none bg-white grid place-content-center'>
            <Logo />
            <SignUpForm status={setSubmitStatus} processing={setIsProcessing} />
          </article>
        </div>
      </main>
    </>
  );
}
